version: 0.0
os: linux
files:
  - source: /flask
    destination: /opt/app
  - source: /nginx-conf/hello.conf
    destination: /etc/nginx/conf.d/ #please change tmp to your nginx conf path
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/setup_nginx.sh
      timeout: 300
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start_flask.sh
      timeout: 300
      runas: root